import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const handleSubmit = async(e) => {
    e.preventDefault();
    document.getElementById('buttoning').disabled = true;

    try {
      const response = await fetch("/api/test", {
            method: "GET"
        });
        if (response.status !== 200){
          //console.log("something went wrong");
          //set an error banner here
          alert("ERROR :", response.status)
          document.getElementById('buttoning').disabled = false;
        } else {
          var mainresults = await response.json()
          console.log(mainresults)
          alert("Success! Results: ", mainresults)
          document.getElementById('buttoning').disabled = false;
        }
        //check response, if success is false, dont take them to success page
        } catch (error) {
        //console.log("there was an error submitting", error);
        alert("ERROR: ", error)
        document.getElementById('buttoning').disabled = false;
        }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.p}>
          When you press the button below, an alert should soon appear.
          If a success, you should see Success, with the results in web console. If it is an error, you should see an ERROR alert.
        </h1>
      
        <button id="buttoning" type="submit" onClick={handleSubmit}>Test!</button>
      </main>
      </div>
  )
}
